name = "workers-airtable-form"
type = "javascript"

account_id = "8db20ccb39ffac6d3dbb0d61a5abe53f"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appS3t6hWcD5kbrIh"
AIRTABLE_TABLE_NAME = "Tasks"
FORM_URL = "https://workers-airtable-form-b4h.pages.dev"